Added bcrypt support for htpasswd
verdaccio/monorepo pull request #389
Opened 2020-11-27 12:44 UTC by 0x78f1935

**Feature:**
**htpasswd:**

The following has been addressed in the PR:

*  There is a related issue?
        Probably, there was no support for bcrypt
*  Unit or Functional tests are included in the PR
        Unfortunately I'm unable to run this locally because my IQ is running on windows

**Description:**
Hopefully this will be added to the docker image.
Please let me know if I can do anything else!

2020-12-04 21:30 UTC, juanpicado requested changes
The lint is broken, check the logs. Run `yarn lint` in your branch.

2020-12-04 21:37 UTC, juanpicado commented
1. You need to push the updated `yarn.lock`, just ran `yarn` locally.

2020-12-04 21:52 UTC, juanpicado commented
The version 5 does not support Node 8. https://www.npmjs.com/package/bcrypt#version-compatibility

Furthermore, this library uses C++ dependencies https://github.com/kelektiv/node.bcrypt.js/blob/master/package.json#L32 which force to compiles on install, I'd like do not include that, maybe try something pure JS liek https://github.com/shaneGirish/bcrypt-nodejs or any other option. At Verdaccio 5 I'd like create an standalone version and to achive that I need 0 dependencies related with https://github.com/nodejs/node-gyp

2020-12-04 22:14 UTC, 0x78f1935 commented
Gotcha, thanks for your review!, I see what I can do and apply those changes asap.

2020-12-05 09:03 UTC, juanpicado commented on yarn.lock
> +node-pre-gyp@0.15.0:
I think this lock file does not match, why this have changed if deps didnt'?

2020-12-05 17:07 UTC, closed without merging